#!/bin/bash

#
# Parameters:
#
# [sysdig path]     run backend with custom sysdig executables path
#

if [ ! -z "$1" ] && [ -e "$1" ]
then
    # or use custom path
    SYSDIG_PATH=$1
else
    SYSDIG_PATH='../../../sysdig/build/userspace/sysdig'
fi

copy_sysdig() {
    cd ember-electron/resources

    cp -a ${SYSDIG_PATH}/ ./sysdig/

    mkdir ./sysdig/capture-samples/
    cp ../../capture-samples/502error.scap ./sysdig/capture-samples/
    cp ../../capture-samples/rootkit_install.scap ./sysdig/capture-samples/

    cd ../..
}

copy_sysdig
