#!/bin/bash

NODE_VERSION="v6.11.2"

setup_env() {
    set +eu
    source ~/.bash_profile

    # check if node version is installed otherwise install it
    nvm list | grep -v "default" | grep ${NODE_VERSION}
    if [ ${?} -eq 1 ]; then
        nvm install ${NODE_VERSION}
    fi
    nvm use ${NODE_VERSION}

    set -xeu
}

clean_app() {
    rm -rf node_modules
    rm -rf bower_components
    rm -rf dist
    rm -rf tmp
    rm -rf electron-out
}

clean_addons() {
    cd lib/wsd-core
    rm -rf node_modules
    rm -rf bower_components

    cd ../..

    cd lib/ui-toolkit
    rm -rf node_modules
    rm -rf bower_components

    cd ../..
}

clean_backend() {
    cd ember-electron/backend

    rm -rf node_modules

    cd ../..
}

setup_env
clean_app
clean_addons
clean_backend
