#!/bin/bash

NODE_VERSION="v6.11.2"

setup_env() {
    set +eu
    source ~/.bash_profile

    # check if node version is installed otherwise install it
    nvm list | grep -v "default" | grep ${NODE_VERSION}
    if [ ${?} -eq 1 ]; then
        nvm install ${NODE_VERSION}
    fi
    nvm use ${NODE_VERSION}

    set -xeu

    # Disabling interactive progress bar, and spinners gains 2x performances
    # as stated on https://twitter.com/gavinjoyce/status/691773956144119808
    npm config set progress false
    npm config set spin false

    GIT_BRANCHNAME=$(echo ${GIT_BRANCH} | cut -d"/" -f2)
}

before_build() {
    GH_STATUS="pending"
    GH_DESCRIPTION="Build #${BUILD_NUMBER} started..."
    GH_CONTEXT="jenkins/sysdig-inspect"

    curl 'https://api.github.com/repos/draios/sysdig-inspect/statuses/'"${GIT_COMMIT}"'?access_token='"${AT}"'' \
    -H 'Content-Type: application/json' \
    -X POST \
    -d '{"state": "'"${GH_STATUS}"'", "context": "'"${GH_CONTEXT}"'", "description": "'"${GH_DESCRIPTION}"'", "target_url": "'"${GH_URL}"'"}'
}

after_build() {
    GH_STATUS="success"
    GH_DESCRIPTION="Build #${BUILD_NUMBER} succeeded"
    GH_URL="https://ci.draios.com/view/sysdig-inspect/job/${JOB_NAME}/${BUILD_NUMBER}/"
    GH_CONTEXT="jenkins/sysdig-inspect"

    curl 'https://api.github.com/repos/draios/sysdig-inspect/statuses/'"${GIT_COMMIT}"'?access_token='"${AT}"'' \
    -H 'Content-Type: application/json' \
    -X POST \
    -d '{"state": "'"${GH_STATUS}"'", "context": "'"${GH_CONTEXT}"'", "description": "'"${GH_DESCRIPTION}"'", "target_url": "'"${GH_URL}"'"}'
}

uploadArtifacts() {
    cd electron-out

    zip -ry Sysdig\ Inspect-darwin-x64.zip Sysdig\ Inspect-darwin-x64
    aws s3 sync Sysdig\ Inspect-darwin-x64.zip s3://download.draios.com/dev/sysdig-inspect/${GIT_BRANCHNAME}/${BUILD_NUMBER}/app/mac --acl public-read
    aws s3 sync make s3://download.draios.com/dev/sysdig-inspect/${GIT_BRANCHNAME}/${BUILD_NUMBER}/installers/linux --acl public-read

    cd ..
}

setup_env

before_build

npm run clean
npm run prepare
npm build
npm test
npm run package:mac
npm run make:linux

uploadArtifacts

after_build