#!/bin/bash

#
# Parameters:
#
# -f            run wsysdig frontend [DEFAULT]
# -b            run wsysdig backend with default sysdig executables path
# -b [path]     run wsysdig backend with custom sysdig executables path 
#

setup_env() {
    platform='unknown'
    unamestr=`uname`
    if [[ "$unamestr" == 'Linux' ]]; then
        platform='linux'
    elif [[ "$unamestr" == 'Darwin' ]]; then
        platform='osx'
    fi

    if [[ $platform == 'osx' ]]; then
        SCRIPT=$(greadlink -f $0)
    else
        SCRIPT=$(readlink -f $0)
    fi

    SCRIPT_DIR=$(dirname $SCRIPT)
    APP_DIR=$SCRIPT_DIR/..

    cd $APP_DIR
}

run() {
    if [ "$1" = "F" ]
    then
        # Serve ember app in the current shell
        ./node_modules/.bin/ember serve --proxy http://localhost:3000
    else
        cd ember-electron/backend
        # Run backend in an external shell
        npm start --- -p=${SYSDIG_PATH}
        cd ../..
    fi
}

setup_env

# Default run frontend
RUN_P="F"
if [ ! -z "$1" ] && [ "$1" = "-b" ]
then
    # or run backend
    RUN_P="B"
fi

# Default sysdig executables path
SYSDIG_PATH='../../sysdig/build/userspace/sysdig'
if [ ! -z "$2" ] && [ -e "$2" ]
then
    # or use custom path
    SYSDIG_PATH=$2
fi

run $RUN_P $SYSDIG_PATH
