#!/bin/bash

#
# Parameters:
#
# [sysdig path]     run backend with custom sysdig executables path
#

NODE_VERSION="v6.11.2"

if [ ! -z "$1" ] && [ -e "$1" ]
then
    # or use custom path
    SYSDIG_PATH=$1
else
    SYSDIG_PATH='../../../sysdig/build/userspace/sysdig'
fi

setup_env() {
    set +eu
    source ~/.bash_profile

    # check if node version is installed otherwise install it
    nvm list | grep -v "default" | grep ${NODE_VERSION}
    if [ ${?} -eq 1 ]; then
        nvm install ${NODE_VERSION}
    fi
    nvm use ${NODE_VERSION}

    set -xeu
}

run() {
    cd ember-electron/backend

    npm start --- -p=${SYSDIG_PATH}

    cd ../..
}

setup_env
run
